const PRODUITS = [
{
id: "crevettes-sechees",
nom: "Crevettes séchées",
nomLocal: "Cipakh",
categorie: "mer",
prix: 6.00,
unite: "par 100g",
prixAncien: null,
badge: "Bestseller",
image: "crevette1.webp",
gallery: ["crevette1.webp", "crevette2.webp", "crevette3.webp"],
description: "Pêche artisanale nocturne en duo dans les Îles du Saloum, cuisson à la vapeur, décortiquage à la main, puis séchage au soleil pendant 2 jours. Une méthode 100% traditionnelle, sans additif.",
origine: "Îles du Saloum, Foundiougne — Région de Fatick",
goutPlus: "Aucune sensation de sable sous la dent : la zone argileuse du Saloum garantit une qualité bien supérieure aux crevettes sablonneuses qu'on trouve ailleurs.",
conseil: "Réhydrater à l'eau tiède (jamais chaude) pour préserver le goût. Condiment polyvalent : se marie avec presque tous les plats sénégalais.",
stock: true,
nouveaute: false
},
{
id: "yoxos",
nom: "Yoxos",
nomLocal: "Huîtres séchées",
categorie: "mer",
prix: 6.00,
unite: "par 100g",
prixAncien: null,
badge: null,
image: "yoxos-saloum-1.webp",
gallery: ["yoxos-saloum-1.webp", "yoxos-saloum-2.webp", "yoxos-saloum-3.webp"],
description: "Yoxos (aussi écrit « yokhos ») — cueillette à la main par les femmes du Saloum, sur les racines des palétuviers en pleine mangrove. Bouillies, décoquillées à la main, séchées au soleil. Méthode traditionnelle préservée de génération en génération.",
origine: "Mangrove des Îles du Saloum, Foundiougne — système matriarcal",
goutPlus: "Chair séchée allongée/ovale (à ne pas confondre avec le pagne/coques dont la chair est arrondie). Récolte respectueuse, repos biologique de 6 mois par an.",
conseil: "Condiment aromatique pour rehausser tous les plats traditionnels. Réhydrater à l'eau tiède avant cuisson.",
stock: true,
nouveaute: false
},
{
id: "pagne",
nom: "Pagne (coques)",
nomLocal: "Pagne",
categorie: "mer",
prix: 6.00,
unite: "par 100g",
prixAncien: null,
badge: null,
image: "pagne-conv.webp",
description: "Coques cueillies à la main par les femmes dans la vase de la mangrove — ramassées ou récupérées en plongeant. Bouillies, décoquillées à la main, essorées au filet puis séchées au soleil 2 à 3 jours. Zéro machine, 100% artisanal.",
origine: "Mangrove des Îles du Saloum — système matriarcal",
goutPlus: "Goût agréable de fruits de mer. Chair séchée arrondie (à ne pas confondre avec les yoxos/huîtres dont la chair est allongée). Cueillette limitée : repos biologique de 6 mois par an.",
conseil: "Frais : parfait en sauce spaghetti comme en Italie. Séché : dans tous les thieb et le riz blanc. Réhydrater à l'eau tiède avant cuisson.",
stock: true,
nouveaute: false
},
{
id: "tuffa",
nom: "Tuffa",
nomLocal: "Touffa",
categorie: "mer",
prix: 6.00,
unite: "par 100g",
prixAncien: null,
badge: null,
image: "tuffa.webp",
description: "Escargot de mer des Îles du Saloum, cueilli à la main en même temps que les coques (pagne) dans la mangrove. Sorti de sa coquille puis séché au soleil pendant 3 à 4 jours. Contrairement aux coques qui sont bouillies, le tuffa est séché directement après extraction.",
origine: "Îles du Saloum, Foundiougne — Mangrove",
goutPlus: "Condiment puissant au goût marin concentré. Le séchage direct (sans cuisson préalable) préserve une saveur plus intense que les autres fruits de mer séchés du Saloum.",
conseil: "Assaisonnement pour les sauces et le riz. Même usage que le yeet : émietter dans la sauce en début de cuisson pour parfumer tout le plat.",
stock: true,
nouveaute: false
},
{
id: "yeet-maggi",
nom: "Yeet Maggi",
nomLocal: "Cymbium",
categorie: "mer",
prix: 6.00,
unite: "par 100g",
prixAncien: null,
badge: null,
image: "yeet1.webp",
gallery: ["yeet1.webp", "yeet2.webp", "yeet3.webp", "yeet4.webp", "yeet5.webp", "yeet6.webp"],
description: "Le yeet est un cymbium, gros mollusque marin sorti frais de la mer. Sa chair est tendre comme du beurre. Au Sénégal, il est cuisiné séché et fermenté. Surnommé le « Maggi africain », c'est le condiment roi qui accompagne toutes les recettes et tous les plats.",
origine: "Sénégal — Pêche artisanale côtière",
goutPlus: "Les stars : Yeet Maggi et Yeet Beurre. Avec du gingembre et du bouillon, cette saveur est inimitable. Un petit morceau transforme complètement une sauce grâce à son goût umami puissant.",
conseil: "Émietter dans la sauce en début de cuisson. Se cuisine aussi frais : sel, citron, épices, puis friture dorée avec oignons, poivrons et piment fort. Le résultat est croustillant et addictif.",
stock: true,
nouveaute: false
},
{
id: "guej-yass",
nom: "Guedj Yass",
nomLocal: "",
categorie: "mer",
prix: 6.00,
unite: "par 100g",
prixAncien: 7.00,
badge: null,
image: "guedj-yass-1.webp",
gallery: ["guedj-yass-1.webp", "guedj-yass-3.webp", "guedj-yass-5.webp", "guedj-yass-2.webp", "guedj-yass-4.webp"],
description: "Guedj de yass (sardinelle plate), séché au soleil selon la méthode traditionnelle sénégalaise. Poisson plat à chair fine, goût prononcé et texture ferme. Un classique de la cuisine sénégalaise.",
origine: "Sénégal — Pêche artisanale côtière",
goutPlus: "Le yass séché a un goût intense et salé qui relève puissamment les sauces. Sa forme plate permet un séchage uniforme et une conservation optimale.",
conseil: "Idéal dans le thiéboudienne, le riz au poisson et les sauces à base de tomate. Casser en morceaux avant d'ajouter à la cuisson.",
stock: true,
nouveaute: false
},
{
id: "guej-beurre",
nom: "Guedj Beurre",
nomLocal: "",
categorie: "mer",
prix: 4.00,
unite: "par 100g",
prixAncien: 6.00,
badge: null,
image: "guedji-beurre.webp",
description: "Le guedj le plus connu de la diaspora. Fait à partir de courbine (Berr), un poisson à chair blanche et grasse. Séchage traditionnel au soleil. Goût doux et polyvalent — il passe partout.",
origine: "Sénégal — Pêche artisanale côtière",
goutPlus: "Sa texture grasse et sa saveur douce en font le guedj le plus accessible. Idéal pour débuter si vous ne connaissez pas encore le guedj.",
conseil: "Se marie avec presque tous les plats sénégalais. Incontournable dans le thiéboudienne.",
stock: true,
nouveaute: false
},
{
id: "guej-beur-casamance",
nom: "Guedj Beurre Casamance",
nomLocal: "Guedj Beurre bi Casamance",
categorie: "mer",
prix: 12.00,
unite: "par 300g",
prixAncien: 18.00,
badge: "Casamance",
image: "guedji-beur_casamance.webp",
description: "Même poisson que le Guedj Beurre (courbine/Berr), mais avec un séchage suivi d'un fumage au bois selon la technique casamançaise. Le résultat est un goût beaucoup plus complexe et profond.",
origine: "Casamance — Région sud du Sénégal",
goutPlus: "Le fumage au bois casamançais apporte une dimension fumée unique. C'est la version premium du Guedj Beurre — 3× le prix, mais un goût incomparable.",
conseil: "Idéal pour les sauces qui demandent de la profondeur. À utiliser avec parcimonie, le goût est plus intense que le Beurre classique.",
stock: true,
nouveaute: false
},
{
id: "guej-sol",
nom: "Guedj Sole",
nomLocal: "",
categorie: "mer",
prix: 4.00,
unite: "par 100g",
prixAncien: 6.00,
badge: null,
image: "guedj-sole-1.webp",
gallery: ["guedj-sole-1.webp", "guedj-sole-2.webp", "guedj-sole-3.webp", "guedj-sole-4.webp"],
description: "Guedj de sole, un poisson plat à chair délicate. Séchage traditionnel au soleil. Sa finesse en fait un guedj apprécié pour les sauces légères et parfumées.",
origine: "Sénégal — Pêche artisanale côtière",
goutPlus: "Plus doux que le kong ou le beurre, le guedj de sole apporte une saveur subtile sans dominer le plat. Parfait pour ceux qui préfèrent un goût moins intense.",
conseil: "Se marie bien avec les sauces claires et le riz blanc. Réhydrater avant cuisson pour une texture plus tendre.",
stock: true,
nouveaute: false
},
{
id: "guej-kong",
nom: "Guedj Kong",
nomLocal: "",
categorie: "mer",
prix: 3.00,
unite: "par 100g",
prixAncien: 5.00,
badge: null,
image: "guedj-kong-1.webp",
gallery: ["guedj-kong-1.webp", "guedj-kong-3.webp", "guedj-kong-2.webp", "guedj-kong-4.webp"],
description: "Guedj de mâchoiron (Kong). Avec le Beurre, c'est l'un des 2 guedj les plus connus de la diaspora. Goût prononcé, idéal pour les plats traditionnels.",
origine: "Sénégal — Pêche artisanale côtière",
goutPlus: "Le kong a un goût puissant et caractéristique qui donne du corps aux sauces. C'est le guedj que la diaspora reconnaît les yeux fermés.",
conseil: "Incontournable dans le thiéboudienne et les plats en sauce. Un petit morceau suffit pour parfumer tout le plat.",
stock: true,
nouveaute: false
},
{
id: "guej-tambajang",
nom: "Guedj Tambajang",
nomLocal: "",
categorie: "mer",
prix: 3.00,
unite: "par 100g",
prixAncien: 5.00,
badge: null,
image: "guedj-tambajang-1.webp",
gallery: ["guedj-tambajang-1.webp", "guedj-tambajang-3.webp", "guedj-tambajang-2.webp"],
description: "Guedj de tambajang, petit poisson séché entier. Très utilisé comme condiment dans la cuisine sénégalaise pour son goût concentré et sa praticité.",
origine: "Sénégal — Pêche artisanale côtière",
goutPlus: "Sa petite taille permet un séchage complet qui concentre intensément les saveurs. Le tambajang est le guedj du quotidien, celui qu'on ajoute dans presque tout.",
conseil: "Ajouter entier ou émietter dans les sauces en début de cuisson. Excellent dans les soupes, le domoda et les plats de riz.",
stock: true,
nouveaute: false
},
{
id: "guej-toumboulan",
nom: "Guedj Toumboulan",
nomLocal: "",
categorie: "mer",
prix: 3.00,
unite: "par 100g",
prixAncien: 5.00,
badge: "Rare",
image: "toumbulan.webp",
gallery: ["toumbulan.webp", "toumbulan1.webp", "toumbulan2.webp"],
description: "Cartilages séchés d'ailerons de raies ou de requin (Gaindé Guéth = Lion de la mer). Très très rare — difficile à obtenir. Accélérateur de goût pour les condiments.",
origine: "Sénégal — Pêche artisanale",
goutPlus: "Son secret : il épaissit la sauce grâce à un effet gélatine naturel. Une sauce épaisse = signe d'un bon thiéboudienne. C'est le guedj des connaisseurs.",
conseil: "À ajouter dans les sauces pour épaissir et intensifier le goût. Un tout petit morceau suffit.",
stock: true,
nouveaute: false
},
{
id: "guerte-tooy",
nom: "Guerte Tooy",
nomLocal: "Arachides grillées",
categorie: "cereales",
prix: 8.00,
unite: "par kg",
prixAncien: null,
badge: null,
image: "guerte-toye.webp",
description: "Arachides grillées à sec (guerte tooy), snack populaire au Sénégal. Grillées artisanalement dans du sable chaud pour une cuisson uniforme et un croquant parfait.",
origine: "Sénégal — Bassin arachidier (Kaolack, Kaffrine)",
goutPlus: "Le grillage au sable chaud donne un goût et un croquant impossibles à reproduire au four. L'arachide sénégalaise a un goût plus intense que les cacahuètes européennes.",
conseil: "À grignoter nature ou à utiliser pour préparer la pâte d'arachide maison. Se conserve dans un endroit sec.",
stock: false,
nouveaute: false
},
{
id: "kongfume",
nom: "Kongfume",
nomLocal: "Kong fumé",
categorie: "mer",
prix: 30.00,
unite: "par 500g",
prixAncien: 35.00,
badge: "Fumé",
image: "kong-fume-sec.webp",
description: "Mâchoiron (kong) fumé puis séché. Double transformation : le fumage apporte une saveur boisée profonde, le séchage assure la conservation. Le résultat est un goût incomparable, plus complexe que le guedj kong classique.",
origine: "Sénégal — Pêche artisanale côtière, fumage traditionnel",
goutPlus: "Le fumage au bois donne au kong une dimension aromatique que le simple séchage n'atteint pas. C'est la version premium pour les sauces qui demandent de la profondeur.",
conseil: "Casser en morceaux et ajouter dans les sauces. Le goût fumé se libère progressivement pendant la cuisson. Parfait pour le thiéboudienne et les soupes.",
stock: true,
nouveaute: false
},
{
id: "kongfume-gambie",
nom: "Kongfume Gambie",
nomLocal: "Kong fumé de Gambie",
categorie: "mer",
prix: 30.00,
unite: "par 500g",
prixAncien: null,
badge: "Gambie",
image: "kong-fume1.webp",
description: "Kong fumé importé de Gambie. Même poisson (mâchoiron) mais fumé selon la technique gambienne, qui donne un résultat légèrement différent du fumage sénégalais.",
origine: "Gambie — Pêche artisanale, fumage traditionnel gambien",
goutPlus: "Le fumage gambien est réputé pour son intensité. Le kong de Gambie a un goût fumé plus prononcé, apprécié par ceux qui recherchent un arôme boisé puissant.",
conseil: "Même utilisation que le kongfumé sénégalais. À doser selon votre préférence, le goût fumé étant plus marqué.",
stock: true,
nouveaute: false
},
{
id: "pack-saloum",
nom: "Pack Saloum",
nomLocal: "Pack bi Saloum",
categorie: "mer",
prix: 60.00,
unite: "par kg",
prixAncien: null,
badge: "Pack 4 produits",
image: "packsaloum-sachetdebout1.webp",
description: "4 trésors des Îles du Saloum réunis : Tuffa + Yoxos + Cipakh (crevettes) + Pagne (coques). Ces 4 produits ne sont jamais disponibles en même temps — cette rareté justifie le pack.",
origine: "Îles du Saloum — Patrimoine UNESCO",
goutPlus: "Chaque produit vient de la même zone (mangrove du Saloum) mais avec des goûts totalement différents. Ensemble, ils couvrent tous les plats traditionnels.",
conseil: "Le cadeau parfait pour quelqu'un qui connaît la cuisine sénégalaise. Ou pour découvrir 4 saveurs du Saloum d'un coup.",
stock: true,
nouveaute: false
},
{
id: "netetu-dom",
nom: "Netetu Dom",
nomLocal: "Netetou",
categorie: "epices",
prix: 5.00,
unite: "par 100g",
prixAncien: 6.00,
badge: null,
image: "netetou-dome.webp",
description: "Graines de néré bouillies, fermentées puis séchées. Condiment emblématique de la cuisine ouest-africaine. Origine principale : Mali et Casamance (Sédhiou/Kolda). Circuit court, emballé sous vide pour neutraliser l'odeur.",
origine: "Mali & Casamance (Sédhiou, Kolda) — Circuit court",
goutPlus: "Le netetou est un exhausteur de goût naturel. Sous vide = pas d'odeur au transport, mais tout le goût une fois en cuisine.",
conseil: "Émietter dans les sauces en début de cuisson. Indispensable dans le mafé et de nombreux plats sénégalais.",
stock: true,
nouveaute: false
},
{
id: "netetu-barre",
nom: "Netetu Barre",
nomLocal: "Netetou en barre",
categorie: "epices",
prix: 5.00,
unite: "par 100g",
prixAncien: 6.00,
badge: null,
image: "netetou-barre.webp",
description: "Netetou (soumbala) pressé en forme de barre compacte. Même produit que le netetu dôme, mais moulé en barre pour un dosage plus facile. L'alternative 100% naturelle aux bouillons industriels.",
origine: "Mali & Casamance (Sédhiou, Kolda) — Circuit court",
goutPlus: "Format pratique : on casse la quantité voulue directement de la barre. Exhausteur de goût naturel qui booste le goût de tous les plats sans additif chimique.",
conseil: "Casser un morceau et émietter dans la sauce. Remplace avantageusement les cubes aromatiques industriels dans le mafé, le thiéboudienne et tous les plats en sauce.",
stock: true,
nouveaute: false
},
{
id: "netetu-mix",
nom: "Netetu Mix",
nomLocal: "Netetou mixte",
categorie: "epices",
prix: 15.00,
unite: "par 200g",
prixAncien: 20.00,
badge: "Mix",
image: "netetou-mixte.webp",
description: "Assortiment de netetou sous plusieurs formes (dôme, barre, poudre) pour découvrir et comparer. Idéal pour ceux qui veulent tester les différentes textures et trouver leur préférence.",
origine: "Mali & Casamance (Sédhiou, Kolda) — Circuit court",
goutPlus: "Le pack découverte du netetou : chaque forme a sa texture et son usage en cuisine. Le dôme pour les grosses sauces, la barre pour doser, la poudre pour saupoudrer.",
conseil: "Tester chaque forme sur un plat différent pour trouver celle qui vous convient. Emballé sous vide pour neutraliser l'odeur au transport.",
stock: true,
nouveaute: false
},
{
id: "netetu-poudre",
nom: "Netetu simple poudre",
nomLocal: "Netetou poudre",
categorie: "epices",
prix: 5.00,
unite: "par 100g",
prixAncien: 6.00,
badge: null,
image: "netetou-poudre.webp",
description: "Netetou (soumbala) réduit en poudre fine. Le format le plus pratique pour saupoudrer directement dans les plats. Se dissout instantanément dans les sauces.",
origine: "Mali & Casamance (Sédhiou, Kolda) — Circuit court",
goutPlus: "La poudre se fond dans la sauce sans laisser de morceaux. Dosage ultra-précis. Même goût profond que le netetou en dôme ou en barre.",
conseil: "Saupoudrer directement dans la sauce ou sur les oeufs, les légumes sautés. Le format idéal pour une utilisation quotidienne rapide.",
stock: true,
nouveaute: false
},
{
id: "sauce-netetu-beugeuc",
nom: "Sauce Netetu Beugeuc",
nomLocal: "Sauce netetou beugeuc",
categorie: "epices",
prix: 10.00,
unite: "250g",
prixAncien: null,
badge: "Sauce",
image: "sauce-netetou.webp",
description: "Sauce prête à l'emploi à base de netetou et de feuilles de bissap (beugeuc). Préparée de manière artisanale, il suffit de l'ajouter directement dans votre plat en cours de cuisson.",
origine: "Sénégal — Préparation artisanale",
goutPlus: "Le mariage netetou + feuilles de bissap donne une sauce umami avec une touche d'acidité végétale. Un goût qu'on ne peut pas reproduire avec des cubes.",
conseil: "Ajouter 2 à 3 cuillères dans la sauce en cours de cuisson. Parfait pour le mafé, le soupou kandia et tous les plats en sauce épaisse.",
stock: true,
nouveaute: false
},
{
id: "beugeuc-feuille-bissap",
nom: "Beugeuc Feuille Bissap",
nomLocal: "Beugeuc bi",
categorie: "epices",
prix: 10.00,
unite: "300g",
prixAncien: 15.00,
badge: "Bissap",
image: "beugeuth-bissap2.webp",
description: "Feuilles de bissap séchées et broyées (beugeuc). Ingrédient de base pour les sauces feuilles sénégalaises. Texture gluante naturelle qui épaissit les sauces.",
origine: "Sénégal — Récolte artisanale",
goutPlus: "Les feuilles de bissap apportent une texture visqueuse caractéristique et un goût végétal unique. Indispensable pour le mafé aux feuilles et le soupou kandia.",
conseil: "Réhydrater dans l'eau tiède puis ajouter à la sauce. Se combine parfaitement avec le netetou pour des sauces riches et onctueuses.",
stock: true,
nouveaute: false
},
{
id: "keciax",
nom: "Keciax",
nomLocal: "Kethiakh",
categorie: "epices",
prix: 3.00,
unite: "par 100g",
prixAncien: 5.00,
badge: null,
image: "kethiakh1.webp",
gallery: ["kethiakh1.webp", "kethiakh2.webp", "kethiakh3.webp"],
description: "Poisson séché et fermenté, plus sec et plus piquant que le guedj classique. Le kethiakh est obtenu par un séchage prolongé qui concentre les saveurs au maximum.",
origine: "Sénégal — Pêche artisanale côtière",
goutPlus: "Goût très concentré, plus fort que le guedj. Son intensité en fait un condiment qu'on utilise en petite quantité pour un maximum d'impact.",
conseil: "Émietter en petits morceaux dans les sauces. Excellent dans le riz au poisson et les plats qui demandent un goût de fond puissant.",
stock: true,
nouveaute: false
},
{
id: "bissap-rouge",
nom: "Bissap Rouge",
nomLocal: "Bissap",
categorie: "epices",
prix: 5.00,
unite: "par 150g",
prixAncien: 6.00,
badge: "Bissap",
image: "Bissap-rouge.webp",
description: "Fleurs d'hibiscus séchées, couleur rouge intense. La base du jus de bissap, boisson emblématique du Sénégal — un goût acidulé que la diaspora compare au Vimto.",
origine: "Kaolack / Keur Madiabel — Sénégal",
goutPlus: "Son acidité naturelle rafraîchit sans sucre ajouté. Effet gélifiant naturel (mucilage) unique au bissap de qualité.",
conseil: "Infuser à froid ou à chaud. Ajouter sucre, menthe, fleur d'oranger selon le goût. Se conserve 3-4 jours au frigo.",
stock: true,
nouveaute: false
},
{
id: "bissap-blanc",
nom: "Bissap Blanc",
nomLocal: "Bissap bu weex",
categorie: "epices",
prix: 5.00,
unite: "par 200g",
prixAncien: 6.00,
badge: "Bissap",
image: "Bissap-blanc.webp",
description: "Variété blanche du bissap, plus douce que la rouge. Utilisée autant en jus qu'en cuisine. Son acidité n'influence pas la couleur des plats.",
origine: "Kaolack / Keur Madiabel — Sénégal",
goutPlus: "Plus polyvalent que le rouge : même acidité mais sans colorer. Effet gélifiant naturel (mucilage) pour épaissir les sauces.",
conseil: "En jus : infusion douce, goût plus subtil. En cuisine : dans les sauces où la couleur rouge n'est pas souhaitée.",
stock: false,
nouveaute: false
},
{
id: "bouye-baobab",
nom: "Bouye (poudre baobab)",
nomLocal: "Bouye",
categorie: "epices",
prix: 6.00,
unite: "par 200g",
prixAncien: null,
badge: "Baobab",
image: "poudre-baobab.webp",
description: "Poudre de fruit de baobab (bouye), riche en vitamine C et en fibres. La base du jus de bouye, boisson crémeuse et rafraîchissante emblématique du Sénégal.",
origine: "Sénégal — Cueillette sauvage",
goutPlus: "Goût acidulé et légèrement sucré, texture farineuse qui donne une consistance crémeuse au jus. Superaliment naturel avec 6x plus de vitamine C que l'orange.",
conseil: "Mélanger dans de l'eau froide avec du sucre et de la vanille pour un jus de bouye. Se consomme aussi en smoothie ou mélangé au lait caillé (thiakry).",
stock: true,
nouveaute: false
},
{
id: "puree-piment",
nom: "Purée Piment Fort",
nomLocal: "Kani",
categorie: "epices",
prix: 10.00,
unite: "200g",
prixAncien: 12.00,
badge: "Piment",
image: "kani-puree.webp",
description: "Purée de piment fort artisanale, préparée à partir de piments frais broyés. La sauce secrète du chef pour relever tous les plats sénégalais.",
origine: "Sénégal — Préparation artisanale",
goutPlus: "Piment pur sans conservateur ni additif. Piquant intense mais savoureux, pas juste du feu. Le goût du piment frais est préservé.",
conseil: "Ajouter en fin de cuisson ou servir à côté du plat. Une petite cuillère suffit. Indispensable avec le thiéboudienne et le yassa.",
stock: true,
nouveaute: false
},
{
id: "maad-confi",
nom: "Maad Confi",
nomLocal: "Maad",
categorie: "epices",
prix: 25.00,
unite: "par kg",
prixAncien: null,
badge: "Confiture",
image: "maad-confi2.webp",
description: "Confiture artisanale de maad (Saba senegalensis), fruit sauvage acidulé typique du Sénégal. Préparée de manière traditionnelle avec du sucre. Un goût unique introuvable en supermarché.",
origine: "Sénégal — Cueillette sauvage, fruit de saison",
goutPlus: "Le maad a un goût acidulé-sucré unique, entre le citron vert et la mangue verte. En confiture, cette acidité est adoucie tout en gardant le caractère du fruit.",
conseil: "Se tartine comme une confiture classique. Excellent avec du pain, des crêpes ou mélangé dans un yaourt. Se conserve plusieurs mois au frais.",
stock: true,
nouveaute: false
},
{
id: "maad-fruit",
nom: "Maad Fruit",
nomLocal: "Maad",
categorie: "epices",
prix: 10.00,
unite: "par kg",
prixAncien: null,
badge: "Fruit",
image: "maad-fruit.webp",
description: "Maad frais (Saba senegalensis), fruit sauvage de saison très recherché au Sénégal. Pulpe acidulée et juteuse, consommé nature avec du sel, du sucre ou du piment.",
origine: "Sénégal — Cueillette sauvage, disponibilité saisonnière",
goutPlus: "Fruit de saison rare, disponible seulement quelques mois par an. Son goût acidulé-sucré est addictif. La diaspora en raffole car impossible à trouver en Europe.",
conseil: "Ouvrir le fruit, extraire la pulpe et consommer avec sel, sucre ou piment selon le goût. Quantité limitée à 3kg par commande.",
stock: true,
nouveaute: true,
maxKg: 3
},
{
id: "thiere-champion",
nom: "Thiéré (couscous de mil)",
nomLocal: "Thiéré",
categorie: "cereales",
prix: 18.00,
unite: "par kg",
prixAncien: null,
badge: "🏆 Champion du Monde",
image: "thiere1.webp",
description: "Couscous de mil roulé à la main, le thiéré est la base du plat national sénégalais « thiéré mboum ». Sacré Champion du Monde du couscous en compétition internationale.",
origine: "Sénégal — Roulé à la main de manière artisanale",
goutPlus: "La différence avec un couscous industriel est immédiate : grains irréguliers, texture unique, goût de mil authentique. Le roulage à la main change tout.",
conseil: "Cuire à la vapeur comme un couscous classique. Se sert avec des sauces de légumes (mboum), du lait caillé ou du bouillon de viande.",
stock: true,
nouveaute: false
},
{
id: "arraw-dugup",
nom: "Arraw Dugup (mil)",
nomLocal: "Arraw",
categorie: "cereales",
prix: 18.00,
unite: "par kg",
prixAncien: null,
badge: "Mil",
image: "arraw.webp",
description: "Granules de mil roulées à la main, plus grosses que le thiéré. Le arraw est la base de bouillies traditionnelles sénégalaises, nourrissantes et réconfortantes.",
origine: "Sénégal — Roulé à la main de manière artisanale",
goutPlus: "Texture plus épaisse que le couscous, le arraw donne des bouillies crémeuses et consistantes. Le goût du mil est plus prononcé grâce aux gros grains.",
conseil: "Cuire dans du lait ou de l'eau pour une bouillie épaisse. Ajouter sucre, beurre ou lait caillé selon le goût. Idéal au petit-déjeuner.",
stock: true,
nouveaute: false
},
{
id: "ciakri",
nom: "Thiakry",
nomLocal: "Cere / Thiakry",
categorie: "cereales",
prix: 18.00,
unite: "par kg",
prixAncien: null,
badge: "Couscous",
image: "thiakry1.webp",
description: "Couscous de mil fin roulé à la main, spécialement préparé pour le dessert thiakry. Mélangé avec du lait caillé sucré, de la crème et de la vanille, c'est le dessert sénégalais par excellence.",
origine: "Sénégal — Roulé à la main de manière artisanale",
goutPlus: "Grains fins et réguliers qui absorbent parfaitement le lait caillé. La texture finale est crémeuse et granuleuse à la fois, un contraste addictif.",
conseil: "Mélanger avec du lait caillé (soow), sucre, crème liquide, vanille et muscade. Servir frais. Le dessert star des cérémonies sénégalaises.",
stock: true,
nouveaute: false
},
{
id: "sankal-duggup",
nom: "Sankal Duggup",
nomLocal: "Sankal",
categorie: "cereales",
prix: 9.00,
unite: "500g",
prixAncien: null,
badge: null,
image: "sankal.webp",
description: "Semoule de mil grossière, utilisée pour préparer le fondé (bouillie traditionnelle) et d'autres plats à base de mil. Texture plus rustique que le thiéré.",
origine: "Sénégal — Transformation artisanale du mil",
goutPlus: "Le sankal a un goût de mil plus brut et terreux. Sa texture grossière donne des plats plus consistants et rassasiants.",
conseil: "Cuire dans l'eau ou le lait pour un fondé. Se sert chaud avec du lait caillé sucré ou une sauce de légumes.",
stock: true,
nouveaute: false
},
{
id: "niebe-saloum",
nom: "Niebe Saloum",
nomLocal: "Niébé",
categorie: "cereales",
prix: 5.00,
unite: "250g",
prixAncien: 6.00,
badge: "Saloum",
image: "niebe-saloum.webp",
description: "Haricots niébé des Îles du Saloum, petits haricots à oeil noir riches en protéines. Aliment de base de la cuisine sénégalaise, cultivé dans les sols fertiles du Saloum.",
origine: "Îles du Saloum — Culture traditionnelle",
goutPlus: "Le niébé du Saloum est réputé pour sa cuisson rapide et sa saveur douce. Plus tendre que les variétés importées grâce au terroir.",
conseil: "Tremper 2h puis cuire. Se cuisine en ragoût, en accompagnement du riz, ou en accara (beignets de niébé). Riche en protéines végétales.",
stock: true,
nouveaute: false
},
{
id: "guerte-noflay",
nom: "Guerte Noflay",
nomLocal: "Poudre d'arachide",
categorie: "cereales",
prix: 5.00,
unite: "par 250g",
prixAncien: 7.00,
badge: "Poudre arachide",
image: "Guerte-noflay.webp",
description: "Poudre d'arachide grillée finement moulue. Ingrédient de base de nombreux plats sénégalais emblématiques. Prête à l'emploi, il suffit de l'ajouter à la sauce.",
origine: "Sénégal — Bassin arachidier",
goutPlus: "Arachides grillées puis moulues : le goût est plus intense qu'une poudre d'arachide industrielle. Se dissout facilement dans les sauces chaudes.",
conseil: "Délayer dans un peu d'eau tiède avant d'ajouter à la sauce pour éviter les grumeaux. Indispensable dans le mbakhalou saloum, le ngourbane, le lakhou thiakhane et le thiéré mboum.",
stock: true,
nouveaute: false
},
{
id: "tiguadegue-500",
nom: "Tiguadegue (pâte d'arachide)",
nomLocal: "Tigadégué",
categorie: "beurres",
prix: 12.00,
unite: "500g",
prixAncien: null,
badge: "Pâte arachide",
image: "tiagadegue.webp",
description: "Pâte d'arachide pure 100% artisanale, fabriquée à partir d'arachides sénégalaises grillées et broyées. Sans sucre, sans huile de palme, sans additif. La vraie pâte d'arachide.",
origine: "Sénégal — Fabrication artisanale",
goutPlus: "Texture épaisse et goût d'arachide grillée intense. Rien à voir avec les pâtes d'arachide industrielles diluées. 100% arachide, rien d'autre.",
conseil: "Base du mafé et du domoda. Se tartine aussi sur du pain. Délayer dans un peu d'eau chaude avant d'ajouter à la sauce.",
stock: true,
nouveaute: false
},
{
id: "tigadegue-250",
nom: "Tigadégué",
nomLocal: "Tigadégué",
categorie: "beurres",
prix: 6.00,
unite: "par 250g",
prixAncien: null,
badge: "Pâte arachide",
image: "tiagadegue.webp",
description: "Format 250g de la pâte d'arachide artisanale. Idéal pour tester ou pour une consommation occasionnelle. Même qualité que le format 500g.",
origine: "Sénégal — Fabrication artisanale",
goutPlus: "Petit format pratique, même pâte d'arachide 100% pure. Parfait pour un mafé pour 4 personnes.",
conseil: "Un pot de 250g suffit pour un mafé familial. Conserver au frais après ouverture.",
stock: true,
nouveaute: false
},
{
id: "diwnior-500",
nom: "Diwnior (beurre clarifié)",
nomLocal: "Diw nior",
categorie: "beurres",
prix: 20.00,
unite: "par 0,5L",
prixAncien: 25.00,
badge: "Beurre vache",
image: "diwnior.webp",
description: "Beurre clarifié traditionnel sénégalais, fabriqué à partir de lait de vache peul. Fondu, filtré et purifié selon la méthode ancestrale. Goût riche et noisette.",
origine: "Sénégal — Élevage peul traditionnel",
goutPlus: "Le diw nior a un goût de noisette prononcé impossible à retrouver dans le beurre clarifié occidental. C'est le ghee sénégalais, mais avec un caractère unique.",
conseil: "Pour la cuisson (supporte les hautes températures) ou en touche finale sur le riz, le couscous ou le fondé. Un peu suffit, le goût est puissant.",
stock: false,
nouveaute: false
},
{
id: "diwnior-1l",
nom: "Diwnior (beurre clarifié)",
nomLocal: "Diw nior",
categorie: "beurres",
prix: 40.00,
unite: "par 1L",
prixAncien: null,
badge: "Beurre vache",
image: "diwnior.webp",
description: "Format 1L du beurre clarifié traditionnel peul. Pour les grandes familles ou les utilisateurs réguliers. Même qualité artisanale que le format 0,5L.",
origine: "Sénégal — Élevage peul traditionnel",
goutPlus: "Grand format plus économique. Le diw nior se conserve longtemps sans réfrigération grâce à la clarification.",
conseil: "Conserver à température ambiante dans un endroit sec. Se solidifie au froid, fond à température ambiante.",
stock: false,
nouveaute: false
},
{
id: "diwtir-pure",
nom: "Diwtir Pure",
nomLocal: "Diw tir",
categorie: "beurres",
prix: 25.00,
unite: "par 1L",
prixAncien: 30.00,
badge: "Huile",
image: "diwtir.webp",
description: "Huile de palme rouge non raffinée, extraite de manière artisanale. Couleur rouge-orangée naturelle, riche en carotènes et en vitamine A. L'huile traditionnelle de la cuisine ouest-africaine.",
origine: "Sénégal — Extraction artisanale",
goutPlus: "Goût fruité et terreux caractéristique, couleur rouge vif naturelle. Rien à voir avec l'huile de palme industrielle raffinée : ici c'est du pur jus, non traité.",
conseil: "Indispensable dans le thiéboudienne (c'est elle qui donne la couleur rouge au riz). Utilisée aussi dans les sauces, le mafé et la friture. Un incontournable de la cuisine sénégalaise.",
stock: true,
nouveaute: false
},
{
id: "lem-miel",
nom: "Lem miel Pure",
nomLocal: "Lem",
categorie: "beurres",
prix: 25.00,
unite: "1,5L",
prixAncien: 27.00,
badge: "Miel",
image: "lem-pure.webp",
description: "Miel pur non pasteurisé, récolté de manière traditionnelle au Sénégal. Non chauffé, non filtré, conserve tous ses enzymes et nutriments. Format généreux de 1,5L.",
origine: "Sénégal — Apiculture traditionnelle",
goutPlus: "Miel brut aux arômes floraux complexes, bien différent des miels industriels. Chaque récolte a un goût unique selon les fleurs butinées.",
conseil: "En tartine, dans le thé, le lait chaud ou les tisanes. Se cristallise naturellement avec le temps (signe de qualité, pas de défaut).",
stock: true,
nouveaute: false
},
{
id: "thiof-decoupe",
nom: "Thiof découpé",
nomLocal: "Thiof",
categorie: "frais",
prix: 55.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "thiof.webp",
description: "Thiof (mérou blanc) découpé en tranches, congelé et conditionné en carton de 5kg. Le poisson noble du Sénégal, celui du vrai thiéboudienne. Chair blanche, ferme et savoureuse.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur. Idéal pour le thiéboudienne, grillé ou en sauce. Le poisson roi de la cuisine sénégalaise.",
stock: false,
nouveaute: false
},
{
id: "diargne-colafil",
nom: "Diarégne Colafil",
nomLocal: "Diarégne",
categorie: "frais",
prix: 49.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "sompate2.webp",
description: "Diarégne (pageot) découpé en filets (colafil), congelé en carton de 5kg. Poisson à chair blanche et délicate, très apprécié dans la cuisine sénégalaise.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur. Se cuisine grillé, en sauce ou frit. Chair fine qui se défait facilement.",
stock: false,
nouveaute: false
},
{
id: "beurre-capitaine",
nom: "Beurre (Capitaine)",
nomLocal: "Berr / Capitaine",
categorie: "frais",
prix: 45.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "thiof4.webp",
description: "Capitaine (courbine/beurre) congelé en carton de 5kg. Poisson à chair blanche et grasse, c'est le même poisson qui donne le guedj beurre une fois séché. Frais, il est encore meilleur.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur. Parfait grillé, en thiéboudienne ou en sauce. Sa chair grasse reste moelleuse à la cuisson.",
stock: false,
nouveaute: false
},
{
id: "chanchar-dieye",
nom: "Chanchar (Diéye)",
nomLocal: "Diéye",
categorie: "frais",
prix: 25.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "yakh4.webp",
description: "Chanchar (diéye) congelé en carton de 5kg. Petit poisson savoureux à prix accessible, très populaire dans la cuisine quotidienne sénégalaise.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur. Excellent frit, en sauce tomate ou dans le riz au poisson. Le poisson du quotidien par excellence.",
stock: false,
nouveaute: false
},
{
id: "poisson-eau-douce",
nom: "Poisson Eau Douce",
categorie: "frais",
prix: 10.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "sompate3.webp",
description: "Assortiment de poissons d'eau douce congelés en carton de 5kg. Provenant des fleuves et rivières du Sénégal. Prix imbattable pour une quantité généreuse.",
origine: "Sénégal — Pêche fluviale",
conseil: "Décongeler au réfrigérateur. Se cuisine en sauce, frit ou grillé. Idéal pour les grandes familles grâce au rapport quantité/prix.",
stock: false,
nouveaute: false
},
{
id: "yaye-boye",
nom: "Yaye Boye",
nomLocal: "Yaboye",
categorie: "frais",
prix: 7.50,
unite: "/ kilo",
prixAncien: null,
badge: "Au kilo",
image: "yaboye.webp",
description: "Sardinelles fraîches congelées (yaboye), vendues au kilo. Le poisson le plus consommé au Sénégal, base de nombreux plats du quotidien.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur. Se frit, se grille ou se cuisine en sauce tomate. Le poisson populaire par excellence, savoureux et économique.",
stock: false,
nouveaute: false
},
{
id: "poisson-sompate",
nom: "Poisson Sompate",
nomLocal: "Sompate",
categorie: "frais",
prix: 45.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "sompate.webp",
description: "Sompate congelé en carton de 5kg. Poisson de mer à chair ferme et goûteuse, très apprécié grillé ou en sauce. Un des poissons préférés de la diaspora.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur. Excellent grillé au charbon avec une sauce oignon-citron, ou en thiéboudienne.",
stock: false,
nouveaute: false
},
{
id: "tilapia-rouge",
nom: "Tilapia Rouge",
nomLocal: "Tilapia",
categorie: "frais",
prix: 22.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "yakh.webp",
description: "Tilapia rouge congelé en carton de 5kg. Poisson d'élevage à chair blanche et douce, apprécié pour sa polyvalence en cuisine et son prix accessible.",
origine: "Sénégal — Élevage piscicole",
conseil: "Décongeler au réfrigérateur. Se cuisine de toutes les façons : frit, grillé, en sauce ou au four. Chair douce qui plaît à tous.",
stock: false,
nouveaute: false
},
{
id: "seude-baracouda",
nom: "Seude Baracouda",
nomLocal: "Seude",
categorie: "frais",
prix: 40.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "seude.webp",
description: "Barracuda (seude) congelé en carton de 5kg. Grand poisson prédateur à chair ferme et goûteuse. Apprécié pour sa texture dense qui tient bien à la cuisson.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur. Idéal grillé ou en darnes dans le thiéboudienne. Sa chair ferme ne se défait pas à la cuisson.",
stock: false,
nouveaute: false
},
{
id: "yakh-carpe-rouge",
nom: "Yakh (Carpe Rouge)",
nomLocal: "Yakh",
categorie: "frais",
prix: 60.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "yakh2.webp",
description: "Carpe rouge (yakh) congelée en carton de 5kg. Poisson noble à chair rouge, ferme et savoureuse. Considéré comme un poisson de fête au Sénégal.",
origine: "Sénégal — Pêche artisanale",
conseil: "Décongeler au réfrigérateur. Poisson de choix pour les grandes occasions. Se cuisine grillé, en sauce ou en thiéboudienne de luxe.",
stock: false,
nouveaute: false
},
{
id: "iler-bi",
nom: "Iler Bi (Plapla)",
nomLocal: "Iler",
categorie: "frais",
prix: 45.00,
unite: "carton 5kg",
prixAncien: null,
badge: "Carton 5kg",
image: "iler.webp",
description: "Iler bi (plapla) congelé en carton de 5kg. Poisson plat à chair fine et délicate, très recherché pour sa saveur subtile.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur. Se cuisine frit (croustillant) ou en sauce légère. Sa forme plate permet une cuisson rapide et uniforme.",
stock: false,
nouveaute: false
},
{
id: "melange-poisson-10kg",
nom: "Mélange de Poisson 10kg",
categorie: "frais",
prix: 110.00,
unite: "carton 10kg",
prixAncien: null,
badge: "⭐ Best Deal",
image: "melange-poisson.webp",
description: "Carton de 10kg avec un mélange de plusieurs espèces de poissons congelés. Le meilleur rapport quantité/prix du catalogue. Idéal pour stocker et varier les plats.",
origine: "Sénégal — Pêche artisanale côtière",
conseil: "Décongeler au réfrigérateur selon le besoin. Chaque espèce se cuisine différemment : frit, grillé, en sauce. De quoi varier les repas pendant des semaines.",
stock: false,
nouveaute: false
}
];
function formatPrix(prix) {
return prix.toFixed(2).replace('.', ',') + ' €';
}
function buildWhatsAppUrl(nom) {
const msg = encodeURIComponent('Bonjour, je souhaite commander : ' + nom);
return 'https://wa.me/33652650395?text=' + msg;
}
function buildProdCard(p) {
const imgContent = p.image
? `<img alt="${p.nom}" src="${p.image}" style="width:100%;height:100%;object-fit:cover;"/>`
: `<div style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;font-size:3rem;">📦</div>`;
let badgeHtml = '';
if (!p.stock) {
badgeHtml = `<div class="prod-badge" style="background:#c0392b;color:#fff;">Rupture de stock</div>`;
} else if (p.nouveaute) {
badgeHtml = `<div class="prod-badge" style="background:#2ecc71;color:#fff;">Nouveau</div>`;
} else if (p.badge) {
const isSpecial = p.badge === '⭐ Best Deal';
const style = isSpecial ? ' style="background:#c9a84c;color:#100d08;"' : '';
badgeHtml = `<div class="prod-badge"${style}>${p.badge}</div>`;
}
const prixAncienHtml = p.prixAncien
? `<span class="prod-price-old">${formatPrix(p.prixAncien)}</span>`
: '';
const nomEsc = p.nom.replace(/'/g, "\\'");
const imgEsc = (p.image || '').replace(/'/g, "\\'");
const btnHtml = p.stock
? `<button class="btn-sm" onclick="cartSystem.add({name:'${nomEsc}',price:${p.prix},unit:'${p.unite}',img:'${imgEsc}',cat:'${p.categorie}'})">🛒 Ajouter</button>`
: `<span class="btn-sm" style="opacity:.35;cursor:not-allowed;pointer-events:none;">Indisponible</span>`;
return `
<div class="prod-card reveal${!p.stock ? ' out-of-stock' : ''}" data-cat="${p.categorie}" data-id="${p.id}">
<div class="prod-img-shell" onclick="openProdModal('${p.id}')">
<div class="prod-img-core">${imgContent}</div>
<div class="prod-img-overlay">${p.nom}</div>
${badgeHtml}
</div>
<div class="prod-body">
<a class="prod-name" href="/produits/${p.id}.html" onclick="openProdModal('${p.id}');return false;" style="cursor:pointer;display:block;text-decoration:none;color:inherit;">${p.nom}</a>
<div class="prod-footer">
<div class="prod-price">${formatPrix(p.prix)} <small>${p.unite}</small>${prixAncienHtml}</div>
${btnHtml}
</div>
</div>
</div>`.trim();
}
function renderProduits() {
const categories = ['mer', 'epices', 'cereales', 'beurres', 'frais'];
categories.forEach(cat => {
const grid = document.querySelector(`#cat-${cat} .cat-grid`);
if (!grid) return;
const produitsCat = PRODUITS.filter(p => p.categorie === cat);
grid.innerHTML = produitsCat.map(buildProdCard).join('');
});
if (window._revealObserver) {
document.querySelectorAll('.prod-card.reveal').forEach(el => {
window._revealObserver.observe(el);
});
}
}
window.PRODUITS = PRODUITS;
document.addEventListener('DOMContentLoaded', renderProduits);